// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDig6jM292KZBJattRNrZ16DAu-Z8UDDQI',
    appId: '1:291236394704:web:b8b240cc2aa004dfc650d5',
    messagingSenderId: '291236394704',
    projectId: 'eatzy-db',
    authDomain: 'eatzy-db.firebaseapp.com',
    storageBucket: 'eatzy-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsvkdfTWMUiyKt3cMLgkdIeanzGjdI0JE',
    appId: '1:291236394704:android:31c913cfb5ff4adac650d5',
    messagingSenderId: '291236394704',
    projectId: 'eatzy-db',
    storageBucket: 'eatzy-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiBO1gvNOB7RWDPvRB2gJ6NcVl8TBrA9M',
    appId: '1:291236394704:ios:6b382e81b91de868c650d5',
    messagingSenderId: '291236394704',
    projectId: 'eatzy-db',
    storageBucket: 'eatzy-db.firebasestorage.app',
    iosBundleId: 'com.example.eatzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiBO1gvNOB7RWDPvRB2gJ6NcVl8TBrA9M',
    appId: '1:291236394704:ios:6b382e81b91de868c650d5',
    messagingSenderId: '291236394704',
    projectId: 'eatzy-db',
    storageBucket: 'eatzy-db.firebasestorage.app',
    iosBundleId: 'com.example.eatzy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDig6jM292KZBJattRNrZ16DAu-Z8UDDQI',
    appId: '1:291236394704:web:b21881319540db2ac650d5',
    messagingSenderId: '291236394704',
    projectId: 'eatzy-db',
    authDomain: 'eatzy-db.firebaseapp.com',
    storageBucket: 'eatzy-db.firebasestorage.app',
  );
}
